version: '2'
services:
  postgres:
    image: postgres:9.6
    environment:
      - DATABASE_NAME=db_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    volumes_from:
      - postgres-data

  postgres-data:
    image: postgres:9.6

  django:
    build:
      context: ./backend/
      dockerfile: Dockerfile-dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/src
    environment:
      - DATABASE_NAME=db_name
      - DATABASE_USERNAME=db_user
      - DATABASE_PASSWORD=db_password
      - DATABASE_PORT=5432
      - MEDIA_DIR=/usr/development/media
    ports:
      - "8000:8000"
    links:
      - postgres
