version: '2'
services:
  django:
    build:
      context: ./ot/
      dockerfile: Dockerfile-dev
    command:
    command: ["./wait-for-postgres.sh", "db", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./ot/:/src
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=12345
      - DATABASE_PORT=5432
      - MEDIA_DIR=/usr/development/media
    ports:
      - "8000:8000"
    links:
      - db

  db:
    image: postgres:10.3
    environment:
      - POSTGRES_PASSWORD=12345
    volumes_from:
      - postgres-data

  postgres-data:
    image: postgres:10.3
